# Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  datasource:
    name: account
    url: jdbc:mysql://localhost:3306/weifly?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Feinik_12354
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

